"""
品牌数据库 - 商业综合体招商品牌库
领导你可以直接在这里加品牌，格式照抄就行
"""
BRANDS = [
    # ===== 餐饮 - 正餐 =====
    {"name": "海底捞", "category": "餐饮", "subcategory": "火锅", "price_range": "中高", "area_need": "800-1200",
     "target_crowd": "全客群", "floors": "B1-4F", "expansion": "活跃", "avg_rent_bear": "150-250元/㎡/月",
     "competitors": ["小龙坎", "巴奴", "呷哺呷哺"], "complementary": ["星巴克", "优衣库", "万达影城"]},
    {"name": "小龙坎", "category": "餐饮", "subcategory": "火锅", "price_range": "中", "area_need": "500-800",
     "target_crowd": "年轻客群", "floors": "2F-4F", "expansion": "活跃", "avg_rent_bear": "120-200元/㎡/月",
     "competitors": ["海底捞", "巴奴"], "complementary": ["喜茶", "泡泡玛特"]},
    {"name": "太二酸菜鱼", "category": "餐饮", "subcategory": "中式正餐", "price_range": "中", "area_need": "300-500",
     "target_crowd": "年轻白领", "floors": "3F-5F", "expansion": "活跃", "avg_rent_bear": "150-220元/㎡/月",
     "competitors": ["江边城外", "探鱼"], "complementary": ["喜茶", "优衣库"]},
    {"name": "西贝莜面村", "category": "餐饮", "subcategory": "西北菜", "price_range": "中高", "area_need": "500-800",
     "target_crowd": "家庭客群", "floors": "3F-4F", "expansion": "稳定", "avg_rent_bear": "130-200元/㎡/月",
     "competitors": [], "complementary": ["孩子王", "万达影城"]},
    {"name": "新荣记", "category": "餐饮", "subcategory": "高端中餐", "price_range": "高", "area_need": "600-1500",
     "target_crowd": "商务/高净值", "floors": "3F-5F", "expansion": "谨慎", "avg_rent_bear": "200-350元/㎡/月",
     "competitors": [], "complementary": ["LV", "Gucci", "高端美容"]},
    {"name": "绿茶餐厅", "category": "餐饮", "subcategory": "中式简餐", "price_range": "低", "area_need": "400-600",
     "target_crowd": "年轻客群/白领", "floors": "3F-5F", "expansion": "活跃", "avg_rent_bear": "100-160元/㎡/月",
     "competitors": ["外婆家", "新白鹿"], "complementary": ["优衣库", "名创优品"]},

    # ===== 餐饮 - 轻餐/饮品 =====
    {"name": "星巴克", "category": "餐饮", "subcategory": "咖啡", "price_range": "中", "area_need": "100-400",
     "target_crowd": "白领/年轻客群", "floors": "1F-2F", "expansion": "活跃", "avg_rent_bear": "200-400元/㎡/月",
     "competitors": ["瑞幸", "Manner", "Peet's"], "complementary": ["优衣库", "Apple Store", "MUJI"]},
    {"name": "瑞幸咖啡", "category": "餐饮", "subcategory": "咖啡", "price_range": "低", "area_need": "30-100",
     "target_crowd": "白领/学生", "floors": "B1-2F", "expansion": "极活跃", "avg_rent_bear": "200-350元/㎡/月",
     "competitors": ["星巴克", "库迪"], "complementary": []},
    {"name": "喜茶", "category": "餐饮", "subcategory": "茶饮", "price_range": "中", "area_need": "80-200",
     "target_crowd": "年轻客群", "floors": "1F-B1", "expansion": "活跃", "avg_rent_bear": "180-300元/㎡/月",
     "competitors": ["奈雪", "霸王茶姬"], "complementary": ["泡泡玛特", "KKV"]},
    {"name": "霸王茶姬", "category": "餐饮", "subcategory": "茶饮", "price_range": "中", "area_need": "80-180",
     "target_crowd": "年轻女性", "floors": "1F-B1", "expansion": "极活跃", "avg_rent_bear": "200-350元/㎡/月",
     "competitors": ["喜茶", "奈雪"], "complementary": ["丝芙兰", "泡泡玛特"]},
    {"name": "Wagas", "category": "餐饮", "subcategory": "轻食", "price_range": "中高", "area_need": "150-300",
     "target_crowd": "白领/健身人群", "floors": "1F-2F", "expansion": "稳定", "avg_rent_bear": "180-280元/㎡/月",
     "competitors": ["gaga", "Moka Bros"], "complementary": ["lululemon", "超级猩猩"]},
    {"name": "Shake Shack", "category": "餐饮", "subcategory": "西式快餐", "price_range": "中高", "area_need": "200-400",
     "target_crowd": "年轻客群/家庭", "floors": "1F-B1", "expansion": "活跃", "avg_rent_bear": "200-350元/㎡/月",
     "competitors": ["Five Guys", "麦当劳旗舰"], "complementary": ["Apple Store", "乐高"]},

    # ===== 零售 - 服饰 =====
    {"name": "优衣库", "category": "零售", "subcategory": "快时尚", "price_range": "中低", "area_need": "1000-3000",
     "target_crowd": "全客群", "floors": "1F-2F", "expansion": "活跃", "avg_rent_bear": "150-250元/㎡/月",
     "competitors": ["ZARA", "H&M", "UR"], "complementary": ["星巴克", "MUJI", "名创优品"]},
    {"name": "ZARA", "category": "零售", "subcategory": "快时尚", "price_range": "中", "area_need": "1500-3500",
     "target_crowd": "年轻客群", "floors": "1F-2F", "expansion": "稳定", "avg_rent_bear": "180-300元/㎡/月",
     "competitors": ["优衣库", "H&M"], "complementary": ["星巴克", "丝芙兰"]},
    {"name": "lululemon", "category": "零售", "subcategory": "运动服饰", "price_range": "高", "area_need": "200-500",
     "target_crowd": "中产/健身人群", "floors": "1F-2F", "expansion": "活跃", "avg_rent_bear": "250-400元/㎡/月",
     "competitors": [], "complementary": ["超级猩猩", "Wagas", "高端超市"]},
    {"name": "UR", "category": "零售", "subcategory": "快时尚", "price_range": "中", "area_need": "1000-2500",
     "target_crowd": "年轻女性", "floors": "1F-2F", "expansion": "活跃", "avg_rent_bear": "150-250元/㎡/月",
     "competitors": ["ZARA", "优衣库"], "complementary": ["丝芙兰", "喜茶"]},

    # ===== 零售 - 美妆/个护 =====
    {"name": "丝芙兰", "category": "零售", "subcategory": "美妆集合", "price_range": "中高", "area_need": "300-600",
     "target_crowd": "年轻女性", "floors": "1F", "expansion": "活跃", "avg_rent_bear": "200-350元/㎡/月",
     "competitors": ["屈臣氏", "调色师"], "complementary": ["ZARA", "UR", "喜茶"]},

    # ===== 零售 - 生活方式 =====
    {"name": "MUJI", "category": "零售", "subcategory": "生活方式", "price_range": "中", "area_need": "600-1500",
     "target_crowd": "中产/年轻客群", "floors": "1F-2F", "expansion": "稳定", "avg_rent_bear": "150-250元/㎡/月",
     "competitors": ["名创优品旗舰"], "complementary": ["优衣库", "星巴克", "书店"]},
    {"name": "泡泡玛特", "category": "零售", "subcategory": "潮玩", "price_range": "中", "area_need": "100-300",
     "target_crowd": "年轻客群", "floors": "B1-1F", "expansion": "极活跃", "avg_rent_bear": "250-500元/㎡/月",
     "competitors": [], "complementary": ["喜茶", "乐高", "电影院"]},
    {"name": "乐高", "category": "零售", "subcategory": "玩具", "price_range": "中高", "area_need": "200-500",
     "target_crowd": "亲子/年轻客群", "floors": "1F-2F", "expansion": "活跃", "avg_rent_bear": "200-350元/㎡/月",
     "competitors": [], "complementary": ["泡泡玛特", "孩子王"]},
    {"name": "KKV", "category": "零售", "subcategory": "生活方式集合", "price_range": "中低", "area_need": "800-2000",
     "target_crowd": "年轻女性", "floors": "B1-1F", "expansion": "活跃", "avg_rent_bear": "120-200元/㎡/月",
     "competitors": ["名创优品"], "complementary": ["喜茶", "泡泡玛特"]},
    {"name": "Apple Store", "category": "零售", "subcategory": "数码", "price_range": "高", "area_need": "500-2000",
     "target_crowd": "全客群", "floors": "1F", "expansion": "谨慎", "avg_rent_bear": "300-600元/㎡/月",
     "competitors": [], "complementary": ["星巴克", "MUJI", "Shake Shack"]},

    # ===== 体验/娱乐 =====
    {"name": "超级猩猩", "category": "体验", "subcategory": "健身", "price_range": "中", "area_need": "300-600",
     "target_crowd": "年轻白领", "floors": "3F-5F", "expansion": "活跃", "avg_rent_bear": "80-150元/㎡/月",
     "competitors": ["乐刻", "威尔仕"], "complementary": ["lululemon", "Wagas"]},
    {"name": "万达影城", "category": "体验", "subcategory": "影院", "price_range": "中", "area_need": "5000-8000",
     "target_crowd": "全客群", "floors": "4F-5F", "expansion": "稳定", "avg_rent_bear": "40-80元/㎡/月",
     "competitors": ["CGV", "博纳"], "complementary": ["海底捞", "星巴克"]},
    {"name": "MELAND", "category": "体验", "subcategory": "儿童乐园", "price_range": "中高", "area_need": "2000-5000",
     "target_crowd": "亲子家庭", "floors": "3F-4F", "expansion": "活跃", "avg_rent_bear": "60-120元/㎡/月",
     "competitors": ["奈尔宝", "卡通尼"], "complementary": ["西贝", "乐高", "孩子王"]},
    {"name": "西西弗书店", "category": "体验", "subcategory": "书店", "price_range": "中", "area_need": "500-1000",
     "target_crowd": "白领/文艺", "floors": "2F-3F", "expansion": "活跃", "avg_rent_bear": "80-150元/㎡/月",
     "competitors": ["言几又", "茑屋"], "complementary": ["星巴克", "MUJI"]},
    {"name": "汤姆熊欢乐世界", "category": "体验", "subcategory": "电玩", "price_range": "低中", "area_need": "1000-3000",
     "target_crowd": "年轻客群/亲子", "floors": "3F-4F", "expansion": "稳定", "avg_rent_bear": "60-100元/㎡/月",
     "competitors": [], "complementary": ["电影院", "美食广场"]},
    {"name": "弹力猩球", "category": "体验", "subcategory": "运动娱乐", "price_range": "中", "area_need": "2000-4000",
     "target_crowd": "年轻客群/亲子", "floors": "3F-5F", "expansion": "活跃", "avg_rent_bear": "60-100元/㎡/月",
     "competitors": [], "complementary": ["轻食", "咖啡"]},

    # ===== 主力店 =====
    {"name": "盒马鲜生", "category": "主力店", "subcategory": "生鲜超市", "price_range": "中高", "area_need": "4000-6000",
     "target_crowd": "家庭/白领", "floors": "B1", "expansion": "活跃", "avg_rent_bear": "60-120元/㎡/月",
     "competitors": ["永辉超级物种", "ole'"], "complementary": ["优衣库", "星巴克"]},
    {"name": "ole'", "category": "主力店", "subcategory": "精品超市", "price_range": "高", "area_need": "2000-4000",
     "target_crowd": "高净值/外籍", "floors": "B1", "expansion": "谨慎", "avg_rent_bear": "80-150元/㎡/月",
     "competitors": ["盒马", "CitySuper"], "complementary": ["LV", "新荣记"]},
    {"name": "迪卡侬", "category": "主力店", "subcategory": "运动集合", "price_range": "低中", "area_need": "3000-6000",
     "target_crowd": "家庭/运动人群", "floors": "B1-2F", "expansion": "稳定", "avg_rent_bear": "50-100元/㎡/月",
     "competitors": [], "complementary": ["优衣库", "电影院", "亲子"]},
    {"name": "孩子王", "category": "主力店", "subcategory": "母婴集合", "price_range": "中", "area_need": "2000-5000",
     "target_crowd": "亲子家庭", "floors": "3F-4F", "expansion": "活跃", "avg_rent_bear": "60-100元/㎡/月",
     "competitors": ["爱婴室"], "complementary": ["西贝", "MELAND", "乐高"]},

    # ===== 体验 - 其他 =====
    {"name": "天真蓝", "category": "体验", "subcategory": "摄影", "price_range": "中", "area_need": "100-300",
     "target_crowd": "年轻客群", "floors": "2F-3F", "expansion": "稳定", "avg_rent_bear": "120-200元/㎡/月",
     "competitors": ["海马体"], "complementary": ["丝芙兰", "喜茶"]},
]
